name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      - name: Tidy
        run: go mod tidy && git diff --exit-code || true
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./... -count=1 -run TestNonexistent || true
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 3m
